# Generated by Django 5.0.7 on 2024-08-07 04:20

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='album',
            options={'ordering': ['id']},
        ),
        migrations.AlterModelOptions(
            name='artist',
            options={'ordering': ['id']},
        ),
        migrations.AlterModelOptions(
            name='song',
            options={'ordering': ['id']},
        ),
        migrations.AlterModelOptions(
            name='track',
            options={'ordering': ['id']},
        ),
        migrations.AddField(
            model_name='song',
            name='image',
            field=models.URLField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
